export const defStrip = [
	{
		id: 'ch',
		digits: 2,
		min: 1,
		max: 16,
		description: 'Channel',
		label: '',
		muteID: 'mute',
		fadeID: 'fad',
		panID: 'pan',
		trimID: 'trim',
		hasLevel: true,
		hasMix: true,
		proc: ['gate', 'insert', 'eq', 'dyn', 'lr', 'hpf', 'invert', 'rtnsw'],
		procPfx: '',
		hasOn: true,
		hasPan: true,
		hasTrim: true,
	},
	{
		id: 'rtn',
		digits: 1,
		min: 1,
		max: 4,
		description: 'FX Return',
		label: 'FX',
		muteID: 'mute',
		fadeID: 'fad',
		panID: 'pan',
		trimID: 'trim',
		hasLevel: true,
		hasMix: true,
		proc: ['eq', 'lr', 'rtnsw'],
		procPfx: '',
		hasOn: true,
		hasPan: true,
		hasTrim: true,
	},
	{
		id: 'fxsend',
		digits: 1,
		min: 1,
		max: 4,
		muteID: 'mute',
		fadeID: 'fad',
		description: 'FX Send',
		label: 'FX',
		hasLevel: false,
		hasMix: true,
		proc: [],
		procPfx: '',
		hasOn: true,
		hasPan: false,
		hasTrim: false,
	},
	{
		id: 'bus',
		digits: 1,
		min: 1,
		max: 6,
		description: 'Bus Master',
		label: 'Bus',
		muteID: 'mute',
		fadeID: 'fad',
		panID: 'pan',
		hasLevel: false,
		hasMix: true,
		proc: ['insert', 'eq', 'dyn', 'lr'],
		procPfx: '',
		hasOn: true,
		hasPan: true,
		hasTrim: false,
	},
	{
		id: 'dca',
		digits: 1,
		min: 1,
		max: 4,
		description: 'DCA',
		label: 'DCA',
		muteID: 'mute',
		fadeID: 'fad',
		hasLevel: false,
		hasMix: false,
		proc: [],
		hasOn: true,
		hasPan: false,
		hasTrim: false,
	},
	{
		id: 'lr',
		digits: 0,
		min: 0,
		max: 0,
		muteID: 'mMute',
		fadeID: 'mFad',
		panID: 'mPan',
		description: 'Main LR',
		label: 'LR',
		hasLevel: false,
		hasMix: true,
		procPfx: 'm_',
		proc: ['insert', 'eq', 'dyn'],
		hasOn: true,
		hasPan: true,
		hasTrim: false,
	},
	{
		id: 'rtn/aux',
		digits: 0,
		min: 0,
		max: 0,
		description: 'USB(x12/x16) or Aux In(x18)',
		label: 'Aux',
		muteID: 'usbMute',
		fadeID: 'usbFad',
		panID: 'usbPan',
		trimID: 'trim',
		hasLevel: true,
		hasMix: true,
		proc: ['eq', 'lr', 'rtnsw'],
		procPfx: 'u_',
		hasOn: true,
		hasPan: true,
		hasTrim: true,
	},
	{
		id: 'config/mute',
		digits: 1,
		min: 1,
		max: 4,
		description: 'Mute Group',
		muteID: 'mute_grp',
		hasLevel: false,
		hasMix: false,
		proc: [],
		hasOn: false,
		hasPan: false,
		hasTrim: false,
	},
]
