export const defStrip = [
	{
		'id': 'ch',
		'digits': 2,
		'min': 1,
		'max': 16,
		'description': 'Channel',
		'label': '',
		'muteID': 'mute',
		'fadeID': 'fad',
		'hasLevel': true,
		'hasMix': true,
		'proc': ['gate', 'insert', 'eq', 'dyn', 'lr'],
		'procPfx': '',
		'hasOn': true,
	},
	{
		'id': 'rtn',
		'digits': 1,
		'min': 1,
		'max': 4,
		'description': 'FX Return',
		'label': 'FX',
		'muteID': 'mute',
		'fadeID': 'fad',
		'hasLevel': true,
		'hasMix': true,
		'proc': ['eq', 'lr'],
		'procPfx': '',
		'hasOn': true,
	},
	{
		'id': 'fxsend',
		'digits': 1,
		'min': 1,
		'max': 4,
		'muteID': 'mute',
		'fadeID': 'fad',
		'description': 'FX Send',
		'label': 'FX',
		'hasLevel': false,
		'hasMix': true,
		'proc': [],
		'procPfx': '',
		'hasOn': true,
	},
	{
		'id': 'bus',
		'digits': 1,
		'min': 1,
		'max': 6,
		'description': 'Bus Master',
		'label': 'Bus',
		'muteID': 'mute',
		'fadeID': 'fad',
		'hasLevel': false,
		'hasMix': true,
		'proc': ['insert', 'eq', 'dyn', 'lr'],
		'procPfx': '',
		'hasOn': true,
	},
	{
		'id': 'dca',
		'digits': 1,
		'min': 1,
		'max': 4,
		'description': 'DCA',
		'label': 'DCA',
		'muteID': 'mute',
		'fadeID': 'fad',
		'hasLevel': false,
		'hasMix': false,
		'proc': [],
		'hasOn': true,
	},
	{
		'id': 'lr',
		'digits': 0,
		'min': 0,
		'max': 0,
		'muteID': 'mMute',
		'fadeID': 'mFad',
		'description': 'Main LR',
		'label': 'LR',
		'hasLevel': false,
		'hasMix': true,
		'procPfx': 'm_',
		'proc': ['insert', 'eq', 'dyn'],
		'hasOn': true,
	},
	{
		'id': 'rtn/aux',
		'digits': 0,
		'min': 0,
		'max': 0,
		'description': 'USB/Aux In',
		'label': 'Aux',
		'muteID': 'usbMute',
		'fadeID': 'usbFad',
		'hasLevel': true,
		'hasMix': true,
		'proc': ['eq'],
		'procPfx': 'u_',
		'hasOn': true,
	},
	{
		'id': 'config/mute',
		'digits': 1,
		'min': 1,
		'max': 4,
		'description': 'Mute Group',
		'muteID': 'mute_grp',
		'hasLevel': false,
		'hasMix': false,
		'proc': [],
		'hasOn': false,
	},
]
